# Generated by Django 5.2.6 on 2025-09-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoAPIapp', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='bookes',
            new_name='books',
        ),
    ]
